general.import = [
  "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[env]
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 17.5

[font.normal]
family = "Hack"

[font.bold]
family = "Hack"

[font.italic]
family = "Hack"

[window]
opacity = 0.8
# startup_mode = "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"
# startup_mode = "Maximize
position =  { x = 398, y = 185 }

[window.dimensions]
columns = 80
lines = 24
